version: '3'

services:
  mariadb-primary:
    container_name: mariadb-primary
    build:
      context: .
      dockerfile: ./Dockerfile-mariadb-restore
    user: root
    restart: unless-stopped
    environment:
      - MYSQL_INITDB_SKIP_TZINFO=Y 
      - MYSQL_ROOT_PASSWORD=linhporo1 
    volumes:
      - /home/linh/Project-assets/totodayshop/mariadb/data/data0:/var/lib/mysql:rw
      - /home/linh/Project-assets/totodayshop/mariadb/config/primary:/etc/mysql/conf.d
    ports:
      - "3307:3306"
    networks:
      - totodayshopnet

  mariadb-secondary:
    container_name: mariadb-secondary
    build:
      context: .
      dockerfile: ./Dockerfile-mariadb-relp
    user: root
    environment:
      - MYSQL_INITDB_SKIP_TZINFO=Y 
      - MYSQL_ROOT_PASSWORD=linhporo1 
    volumes:
      - /home/linh/Project-assets/totodayshop/mariadb/data/data1:/var/lib/mysql:rw
      - /home/linh/Project-assets/totodayshop/mariadb/config/secondary:/etc/mysql/conf.d
    ports:
      - "3308:3306"
    networks:
      - totodayshopnet
  #mongodb 

  mongodb-primary:
    container_name: mongodb-primary
    build:
      context: .
      dockerfile: ./Dockerfile-mongodb-primary
    user: root
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adminLinh
      - MONGO_INITDB_ROOT_PASSWORD=linhporo1
    ports: 
      - "37017:27017"
    volumes:
      - /home/linh/Project-assets/totodayshop/mongodb/data/data0:/data/db
    networks:
      - totodayshopnet
    command: mongod --replSet "totodayrs" --keyFile /etc/auth/key.keyFile  --bind_ip 0.0.0.0 --oplogSize 128 

  mongodb-repl1:
    container_name: mongodb-repl1 
    build:
      context: .
      dockerfile: ./Dockerfile-mongodb-secondary
    user: root
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adminLinh
      - MONGO_INITDB_ROOT_PASSWORD=linhporo1
    ports: 
      - "37018:27017"
    volumes:
      - /home/linh/Project-assets/totodayshop/mongodb/data/data1:/data/db
    networks:
      - totodayshopnet
    command: mongod --replSet "totodayrs" --keyFile /etc/auth/key.keyFile  --bind_ip 0.0.0.0 --oplogSize 128 

  mongodb-repl2:
    container_name: mongodb-repl2 
    build:
      context: .
      dockerfile: ./Dockerfile-mongodb-secondary
    user: root
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adminLinh
      - MONGO_INITDB_ROOT_PASSWORD=linhporo1
    ports: 
      - "37019:27017"
    volumes:
      - /home/linh/Project-assets/totodayshop/mongodb/data/data2:/data/db
    networks:
      - totodayshopnet
    command: mongod --replSet "totodayrs" --keyFile /etc/auth/key.keyFile  --bind_ip 0.0.0.0 --oplogSize 128 

  redis-primary:
    container_name: redis-primary
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile-redis-primary
    ports:
      - "6380:6379"
    networks:
      - totodayshopnet
    volumes:
      - /home/linh/Project-assets/totodayshop/redis/master/conf:/etc/redis:rw
      - /home/linh/Project-assets/totodayshop/redis/master/dump:/etc/redisdump:rw
    command: redis-server /etc/redis/redis.conf

  redis-replica1:
    container_name: redis-replica1
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile-redis-replica
    ports:
      - "6381:6379"
      - "26381:26379"
    networks:
      - totodayshopnet
    volumes:
      - /home/linh/Project-assets/totodayshop/redis/repl/repl1/conf:/etc/redis:rw
      - /home/linh/Project-assets/totodayshop/redis/repl/repl1/dump:/etc/redisdump:rw
      - /home/linh/Project-assets/totodayshop/redis/sentinel/sen1:/etc/redis-sentinel:rw
    command: bash -c "/etc/script/script.sh"   

  redis-replica2:
    container_name: redis-replica2
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile-redis-replica
    ports:
      - "6382:6379"
      - "26382:26379"
    networks:
      - totodayshopnet
    volumes:
      - /home/linh/Project-assets/totodayshop/redis/repl/repl2/conf:/etc/redis:rw
      - /home/linh/Project-assets/totodayshop/redis/repl/repl2/dump:/etc/redisdump:rw
      - /home/linh/Project-assets/totodayshop/redis/sentinel/sen2:/etc/redis-sentinel:rw
    command: bash -c "/etc/script/script.sh"   

  redis-replica3:
    container_name: redis-replica3
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile-redis-replica
    ports:
      - "6383:6379"
      - "26383:26379"
    networks:
      - totodayshopnet
    volumes:
      - /home/linh/Project-assets/totodayshop/redis/repl/repl3/conf:/etc/redis:rw
      - /home/linh/Project-assets/totodayshop/redis/repl/repl3/dump:/etc/redisdump:rw
      - /home/linh/Project-assets/totodayshop/redis/sentinel/sen3:/etc/redis-sentinel:rw
    command: bash -c "/etc/script/script.sh"   

  redis-sentinel4:
    container_name: redis-sentinel4
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile-redis-replica
    ports:
      - "26384:26379"
    networks:
      - totodayshopnet
    volumes:
      - /home/linh/Project-assets/totodayshop/redis/sentinel/sen4:/etc/redis-sentinel
    command: redis-server /etc/redis-sentinel/sentinel.conf --sentinel

  redis-sentinel5:
    container_name: redis-sentinel5
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile-redis-replica
    ports:
      - "26385:26379"
    networks:
      - totodayshopnet
    volumes:
      - /home/linh/Project-assets/totodayshop/redis/sentinel/sen5:/etc/redis-sentinel
    command: redis-server /etc/redis-sentinel/sentinel.conf --sentinel


networks:
  totodayshopnet:
    external: true
    name: totodayshopnet
