# Use an official Apline Linux base image 
FROM mariadb:11.1.2 

COPY ./backup/mariadb/backup_file/backup_mariadb.sql /docker-entrypoint-initdb.d/
COPY ./config-files/mariadb-primaryInit.sql /docker-entrypoint-initdb.d/



